spring.application.name=gateway
server.port=8082

# ------- EUREKA SERVER ----

eureka.client.service-url.defaultZone=http://localhost:8083/eureka

# -------- ROUTES --------

# API SERVICE
spring.cloud.gateway.routes[0].id=api-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# INDEXADOR SERVICE
spring.cloud.gateway.routes[1].id=indexador-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/indexador/**